name: build
on: [push]
jobs:
  x86_64 Clang:
    runs-on: ubuntu-rolling
    steps:
      - run: apt-get update
      - run: apt-get install -y clang git cmake ninja-build pkg-config nodejs
      - run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
      - run: git clone --recurse-submodules https://${{ secrets.GITHUB_TOKEN }}@git.burntcomma.com/${{ github.repository }} ${SHORT_SHA}
      - run: cd ${SHORT_SHA} && git checkout ${{ github.sha }}
      - run: |
          cmake -GNinja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_INSTALL_PREFIX=${PWD}/install/debug \
            -S ${SHORT_SHA} -B debug-work && \
          cmake --build debug-work && \
          cmake --install debug-work
      - run: |
          cmake -GNinja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_INSTALL_PREFIX=${PWD}/install/release \
            -S ${SHORT_SHA} -B release-work && \
          cmake --build release-work && \
          cmake --install release-work
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          overwrite: true
          path: |
            install
